
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const NodeType = {
  INITIAL: 'INITIAL',
  TRIGGER: 'TRIGGER',
  ACTION: 'ACTION',
  CONDITION: 'CONDITION',
  HTTP_REQUEST: 'HTTP_REQUEST',
  MANUAL_TRIGGER: 'MANUAL_TRIGGER'
} as const

export type NodeType = (typeof NodeType)[keyof typeof NodeType]
