import type { RegisteredTool } from "../../shared";

export const internalToolCatalog: RegisteredTool[] = [
  {
    id: "internal.browser_page",
    provider: "INTERNAL",
    displayName: "Browser Page",
    description:
      "Fetch a public web page, extract the title, summary text, and top links.",
    transport: "NONE",
    lifecycle: "READY",
    dangerous: true,
    requiresApproval: false,
    capabilities: ["BROWSER", "HTTP"],
    parameters: [
      {
        key: "url",
        label: "URL",
        description: "Public page URL to visit.",
        type: "string",
        required: true,
      },
      {
        key: "maxChars",
        label: "Max chars",
        description: "Maximum extracted text length to keep.",
        type: "number",
        required: false,
      },
      {
        key: "includeLinks",
        label: "Include links",
        description: "Whether to return the top links found on the page.",
        type: "boolean",
        required: false,
      },
    ],
    tags: ["browser", "research", "workflow-node"],
  },
  {
    id: "internal.http_request",
    provider: "INTERNAL",
    displayName: "HTTP Request",
    description:
      "Call an external HTTP endpoint through the workflow runtime.",
    transport: "NONE",
    lifecycle: "READY",
    dangerous: true,
    requiresApproval: false,
    capabilities: ["HTTP"],
    parameters: [
      {
        key: "url",
        label: "URL",
        description: "Target endpoint URL.",
        type: "string",
        required: true,
      },
      {
        key: "method",
        label: "Method",
        description: "HTTP method to send.",
        type: "string",
        required: true,
      },
      {
        key: "body",
        label: "Body",
        description: "Optional JSON payload.",
        type: "object",
        required: false,
      },
    ],
    tags: ["network", "workflow-node"],
  },
  {
    id: "internal.memory_read",
    provider: "INTERNAL",
    displayName: "Execution Memory Read",
    description:
      "Read the current workflow run memory or a node-scoped memory entry.",
    transport: "NONE",
    lifecycle: "READY",
    dangerous: false,
    requiresApproval: false,
    capabilities: ["MEMORY_READ"],
    parameters: [
      {
        key: "scope",
        label: "Scope",
        description: "Shared or node-scoped memory.",
        type: "string",
        required: true,
      },
      {
        key: "namespace",
        label: "Namespace",
        description: "Memory namespace.",
        type: "string",
        required: true,
      },
      {
        key: "key",
        label: "Key",
        description: "Memory key within the namespace.",
        type: "string",
        required: true,
      },
    ],
    tags: ["memory", "workflow-node"],
  },
  {
    id: "internal.memory_write",
    provider: "INTERNAL",
    displayName: "Execution Memory Write",
    description:
      "Write or merge values into the current workflow run memory.",
    transport: "NONE",
    lifecycle: "READY",
    dangerous: true,
    requiresApproval: false,
    capabilities: ["MEMORY_WRITE"],
    parameters: [
      {
        key: "scope",
        label: "Scope",
        description: "Shared or node-scoped memory.",
        type: "string",
        required: true,
      },
      {
        key: "namespace",
        label: "Namespace",
        description: "Memory namespace.",
        type: "string",
        required: true,
      },
      {
        key: "key",
        label: "Key",
        description: "Memory key within the namespace.",
        type: "string",
        required: true,
      },
      {
        key: "value",
        label: "Value",
        description: "Value to store in execution memory.",
        type: "object",
        required: true,
      },
    ],
    tags: ["memory", "workflow-node"],
  },
  {
    id: "internal.discord_webhook",
    provider: "INTERNAL",
    displayName: "Discord Webhook",
    description: "Post a message to a Discord webhook credential.",
    transport: "NONE",
    lifecycle: "READY",
    dangerous: true,
    requiresApproval: false,
    capabilities: ["MESSAGING"],
    parameters: [
      {
        key: "content",
        label: "Content",
        description: "Message body to send.",
        type: "string",
        required: true,
      },
    ],
    tags: ["messaging", "workflow-node"],
  },
  {
    id: "internal.slack_webhook",
    provider: "INTERNAL",
    displayName: "Slack Webhook",
    description: "Post a message to a Slack webhook credential.",
    transport: "NONE",
    lifecycle: "READY",
    dangerous: true,
    requiresApproval: false,
    capabilities: ["MESSAGING"],
    parameters: [
      {
        key: "content",
        label: "Content",
        description: "Message body to send.",
        type: "string",
        required: true,
      },
    ],
    tags: ["messaging", "workflow-node"],
  },
];
