import type { Edge, Node } from "@xyflow/react";

export type TemplateVariableOption = {
  group: string;
  label: string;
  value: string;
  hint?: string;
};

function formatNodeType(type?: string | null) {
  switch (type) {
    case "AI_TEXT":
      return "AI Text";
    case "LOOP":
      return "Loop";
    case "HTTP_REQUEST":
      return "HTTP Request";
    case "MANUAL_TRIGGER":
      return "Manual Trigger";
    case "WEBHOOK_TRIGGER":
      return "Webhook Trigger";
    case "DISCORD_MESSAGE":
      return "Discord Message";
    case "SLACK_MESSAGE":
      return "Slack Message";
    default:
      return type ?? "Node";
  }
}

function shortNodeId(id: string) {
  return id.slice(-6);
}

function addOption(
  options: TemplateVariableOption[],
  seen: Set<string>,
  option: TemplateVariableOption,
) {
  if (seen.has(option.value)) {
    return;
  }

  seen.add(option.value);
  options.push(option);
}

function buildNodeSpecificOptions(node: Node): TemplateVariableOption[] {
  const group = `Upstream · ${formatNodeType(node.type)} · ${shortNodeId(node.id)}`;
  const options: TemplateVariableOption[] = [
    {
      group,
      label: "Semantic result",
      value: `{{memory.shared.nodesById.${node.id}.result}}`,
      hint: "The best downstream-friendly value from this node.",
    },
    {
      group,
      label: "Raw output",
      value: `{{steps.${node.id}.output}}`,
      hint: "The full executor output for this node.",
    },
    {
      group,
      label: "Shared node snapshot",
      value: `{{memory.shared.nodesById.${node.id}.output}}`,
      hint: "The node output stored in shared execution memory.",
    },
  ];

  if (node.type === "AI_TEXT") {
    options.unshift({
      group,
      label: "AI text",
      value: `{{steps.${node.id}.output.text}}`,
      hint: "The plain text generated by the upstream AI node.",
    });
  }

  if (node.type === "LOOP") {
    options.unshift(
      {
        group,
        label: "Loop value",
        value: `{{steps.${node.id}.output.value}}`,
        hint: "The semantic value being passed across loop iterations.",
      },
      {
        group,
        label: "Loop attempt",
        value: `{{steps.${node.id}.output.attempt}}`,
        hint: "The current loop iteration number for this node.",
      },
      {
        group,
        label: "Loop completion flag",
        value: `{{steps.${node.id}.output.isFinalAttempt}}`,
        hint: "True when the loop reached its final configured iteration.",
      },
    );
  }

  if (node.type === "HTTP_REQUEST") {
    options.unshift(
      {
        group,
        label: "HTTP body",
        value: `{{steps.${node.id}.output.body}}`,
        hint: "The parsed response body from the upstream request.",
      },
      {
        group,
        label: "HTTP status",
        value: `{{steps.${node.id}.output.status}}`,
        hint: "The response status code from the upstream request.",
      },
    );
  }

  if (node.type === "MANUAL_TRIGGER" || node.type === "WEBHOOK_TRIGGER") {
    options.unshift({
      group,
      label: "Trigger body",
      value: `{{steps.${node.id}.output.body}}`,
      hint: "The trigger payload body from the upstream trigger.",
    });
  }

  return options;
}

export function buildTemplateVariableOptions(params: {
  currentNodeId: string;
  nodes: Node[];
  edges: Edge[];
}) {
  const { currentNodeId, nodes, edges } = params;
  const options: TemplateVariableOption[] = [];
  const seen = new Set<string>();
  const nodeById = new Map(nodes.map((node) => [node.id, node]));
  const nodeOrder = new Map(nodes.map((node, index) => [node.id, index] as const));
  const incomingByTarget = new Map<string, string[]>();

  for (const edge of edges) {
    const current = incomingByTarget.get(edge.target) ?? [];
    current.push(edge.source);
    incomingByTarget.set(edge.target, current);
  }

  const ancestorIds: string[] = [];
  const queue = [...(incomingByTarget.get(currentNodeId) ?? [])];
  const visited = new Set<string>();

  while (queue.length > 0) {
    const nodeId = queue.shift();
    if (!nodeId || visited.has(nodeId)) {
      continue;
    }

    visited.add(nodeId);
    ancestorIds.push(nodeId);

    for (const upstreamId of incomingByTarget.get(nodeId) ?? []) {
      queue.push(upstreamId);
    }
  }

  ancestorIds.sort((left, right) => {
    return (nodeOrder.get(left) ?? 0) - (nodeOrder.get(right) ?? 0);
  });

  [
    {
      group: "Current input",
      label: "Semantic input",
      value: "{{input}}",
      hint: "The best downstream-friendly value from upstream nodes.",
    },
    {
      group: "Current input",
      label: "Raw input",
      value: "{{inputRaw}}",
      hint: "The full raw upstream output before semantic mapping.",
    },
    {
      group: "Current input",
      label: "Main input",
      value: "{{inputs.main}}",
      hint: "The semantic value connected to the main input handle.",
    },
    {
      group: "Current input",
      label: "Raw main input",
      value: "{{inputsRaw.main}}",
      hint: "The raw value connected to the main input handle.",
    },
    {
      group: "Run context",
      label: "Execution ID",
      value: "{{execution.id}}",
      hint: "The current execution id.",
    },
    {
      group: "Run context",
      label: "Current attempt",
      value: "{{current.attempt}}",
      hint: "The current execution count for this node inside the run.",
    },
    {
      group: "Run context",
      label: "Trigger source",
      value: "{{trigger.source}}",
      hint: "The current trigger type or source marker.",
    },
    {
      group: "Run context",
      label: "Trigger body",
      value: "{{trigger.body}}",
      hint: "The current trigger payload body.",
    },
    {
      group: "Shared memory",
      label: "Run trigger",
      value: "{{memory.shared.run.trigger}}",
      hint: "The trigger payload persisted in execution memory.",
    },
    {
      group: "Shared memory",
      label: "Run metadata",
      value: "{{memory.shared.run.metadata}}",
      hint: "Workflow and execution metadata for this run.",
    },
    {
      group: "Shared memory",
      label: "Last node result",
      value: "{{memory.shared.run.lastNode.result}}",
      hint: "The last completed node semantic result.",
    },
    {
      group: "Node memory",
      label: "Current node output",
      value: "{{memory.node.run.output}}",
      hint: "The raw output persisted by the current node.",
    },
    {
      group: "Node memory",
      label: "Current node result",
      value: "{{memory.node.run.result}}",
      hint: "The semantic result persisted by the current node.",
    },
  ].forEach((option) => addOption(options, seen, option));

  for (const nodeId of ancestorIds) {
    const node = nodeById.get(nodeId);
    if (!node) {
      continue;
    }

    for (const option of buildNodeSpecificOptions(node)) {
      addOption(options, seen, option);
    }
  }

  return options;
}
